// library creators can't use these properties when adding extensions to this parser.
export const savedProps = [
  'extends',
  'path',
  'childrenIndexes',
  'parentsIndexes',
  'defaultNodeIndex',
  'extendedFlowIndex',
  'id',
  'hasPredefinedName',
  'name',
  'graph',
  'pathsGroups',
  'extendedFlowId',
  'extendedParsedFlow',
  'default_path',
  'extends_flows',
  'hasPredefinedName',
  'extendsFlows',
  'defaultPath',
  'splitters',
  'flows',
]
